// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flmxfwnxxnazlifgtkba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsbXhmd254eG5hemxpZmd0a2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODY0NjYsImV4cCI6MjA2NjU2MjQ2Nn0.fUcIoBw3w_6kK8vfkXJAW5Qb_QhFGIhTN-_QfAUJm9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);